### ISSUE TITLE
MySQLi can't load custom class objects if they contain protected properties

### ISSUE THREAD

**Issue by SharkyKZ** [joomla-framework/database#199]
### Steps to reproduce the issue

Do `$db->loadObjectList('key', SomeClass::class)` when `SomeClass` contains protected properties.

### Expected result

Works.

### Actual result

`Trying to access protected property` error.

### Additional comments

I'm not sure whether this is expected or not because this works fine on PDO drivers.

**Comment by mbabker** [comment]
It’s intended.  The object actually gets manually instantiated and seeded by the MysqliStatement class, whereas with PDO the extension handles it all (I’ve never dig in to the C code but I imagine there is some form of reflection involved to be able to direct set non public properties).  It has to be this way otherwise we lose libmysql compatibility and force mysqlnd only.

**Comment by mbabker** [comment]
We lose libmysql if we try to use the `ext/mysqli` API in the "right" way because it doesn't support certain functions (namely `mysqli_stmt_get_result()`, which means a lot of that logic has to be emulated in userland code).  Look at the master branch of this repo, that does use the API the "right" way and we have checks in it that block libmysql support as a result.

(Note this is the same approach taken by Doctrine for much the same reason, this is why you're generally better off not passing a custom class into these database API functions and using some form of ORM or data mapping layer to convert the database result set to your own class object)

**Comment by mbabker** [comment]
Actually, if I would have done things right when I originally implemented things, `$db->loadObjectList('key', SomeClass::class)` should end up triggering a code path that throws an Exception.  `DatabaseDriver::fetchObject()` should be setting the fetch mode to `FetchMode::CUSTOM_OBJECT` if the class isn't `stdClass`, which isn't a mode that the MySQLi driver supports and will throw an Exception.  Sure, the API technically supports loading in a custom class, but it's limited in nature (class must have public properties or a magic setter) and not feature compatible with what `ext/mysqli` or `ext/pdo` or `ext/sqlsrv` do under the hood so the right action is to trigger the error.

**Comment by SharkyKZ** [comment]
https://github.com/joomla-framework/database/blob/abbfe675d9102c0ae1ec63d746783d3ac9f06dfc/src/Mysqli/MysqliStatement.php#L557-L560
What I meant is, can't we set properties here using Reflection? Or would that break libmysql? Or just be a completely wrong approach?

>$db->loadObjectList('key', SomeClass::class) should end up triggering a code path that throws an Exception.

If exception is always thrown, what's the point of having the custom class option? Shouldn't it be removed eventually in such case?

**Comment by mbabker** [comment]
> What I meant is, can't we set properties here using Reflection? Or would that break libmysql? Or just be a completely wrong approach?

This would need to be benchmarked to determine if there is a performance penalty if we were to do this in userland PHP code (I don't know how `ext/mysqli` or `ext/pdo` or `ext/sqlsrv` deal with this under the hood), and then if there is decided if the performance penalty is worth supporting the feature.

> If exception is always thrown, what's the point of having the custom class option? Shouldn't it be removed eventually in such case?

It would only raise an exception if the driver doesn't support it.  Right now, that would be only the MySQLi driver because of the way the fetching code is written, it will work fine on any PDO implementation or with SQL Server.

**Comment by mbabker** [comment]
(Basically if the fetch mode were being set correctly now, with MySQLi it would hit the default of [this switch](https://github.com/joomla-framework/database/blob/abbfe675d9102c0ae1ec63d746783d3ac9f06dfc/src/Mysqli/MysqliStatement.php#L538-L566) and that would be where the exception comes from, it's not a "Joomla's API doesn't support this in any condition" thing)

**Comment by SharkyKZ** [comment]
I'll look into using reflection. Realistically though, loading results using iterator and instantiating the class manually should be about as efficient as using `loadObjectList()`, right?

**Comment by mbabker** [comment]
Realistically it should be the same (and realistically a proper data mapper or ORM type scenario would be doing just that, probably with Reflection also).

The only thing I worry about is baking that type of code direct into the database driver because to me that doesn't come across as a responsibility of a database connection API to handle.

**Comment by mbabker** [comment]
FYI https://github.com/joomla-framework/database/pull/200 changes things to be "right" as far as flipping the mode and triggering the Exception when using something that isn't `stdClass`.

**Comment by SharkyKZ** [comment]
>The only thing I worry about is baking that type of code direct into the database driver because to me that doesn't come across as a responsibility of a database connection API to handle.

Looks like PHP thinks otherwise with PDO.

Anyways, thanks. I'll update the uses in CMS.

**Comment by mbabker** [comment]
Just for clarity, it's not like it's 100% wrong to use the database APIs to load custom objects (otherwise `PDOStatement::fetchObject()`, `sqlsrv_fetch_object()`, `mysqli_fetch_object()`, and `pg_fetch_object()` wouldn't support it).  But, the way it works under the hood may not be as you intend for an object to work as they typically are direct setting the properties (so if you have setters you intend for something to go through, those won't be used), and if I'm not mistaken there are cases where the class constructors may not be executed or may not be called in the order you'd expect (i.e. `mysqli_fetch_object()` is documented that it sets the properties before calling the constructor).

When using Doctrine's DBAL and ORM, under the hood it's fetching data as plain PHP arrays then using the data mapper to cast that data into a PHP class and not using this feature of the underlying database extensions.

Hence, the reason I suggest that while this part of the API can be made to work, generally it's a better idea to avoid the feature and use your own conversion layer if you need a database row as an object of a specific type.
