### ISSUE TITLE
DatabaseQuery::union BUG?

### ISSUE THREAD

**Issue by bweston92** [joomla-framework/database#2]
I see the to string method looking to see if DatabaseQuery::$type is equal to union but it doesn't get set anywhere in the class is this a bug or am I trying to do it wrong?

**Comment by jbanety** [comment]
This bug still exists.
The union is present in the `DatabaseQuery::__toString()` method at [DatabaseQuery.php#L292](https://github.com/joomla-framework/database/blob/master/src/DatabaseQuery.php#L292).
We can't change query type to union so it is impossible to make an union query.

**Comment by mbabker** [comment]
Someone feel free to submit a pull request with the needed changes then?  I know it isn't as straight forward as setting `$this->type = 'union';` in the `union` method since the union can also be used in other query types (like [this example](https://github.com/joomla/joomla-cms/blob/3.4.3/administrator/components/com_finder/helpers/indexer/query.php#L1294) in the CMS' com_finder component).

**Comment by jbanety** [comment]
Yes. The `__toString()` method needs to be rewrote to handle union properly.
I'll do it in the next few days.

**Comment by bweston92** [comment]
Only 2 years later. Unfortunately I don't have time to debug and create a PR.

**Comment by jbanety** [comment]
Yop. Create union queries with DatabaseQuery class is a very small use case.

**Comment by jbanety** [comment]
Check my [PR#30](https://github.com/joomla-framework/database/pull/30)

**Comment by bweston92** [comment]
Closing as how old it is.
