### ISSUE TITLE
[2.0] Unsupported ROW_NUMBER() function

### ISSUE THREAD

**Issue by sakiss** [joomla-framework/database#213]
https://github.com/joomla-framework/database/blob/4cda5d73eb55ac8a596f261aac08a33d658421fb/src/DatabaseQuery.php#L2475

The function `ROW_NUMBER()` seems to be introduced in MySQL 8.
https://www.mysqltutorial.org/mysql-window-functions/mysql-row_number-function/

Though Joomla 4 seems to require MySQL 5.6 as a minimum.
https://developer.joomla.org/news/788-joomla-4-on-the-move.html

Is that feature checked against MySQL version lower to 8 ?

This maybe related with issues regarding the records ordering in the database tables.
e.g. https://github.com/joomla/joomla-cms/issues/23905

For versions lower to 8 it suggests ways to emulate it.
https://www.mysqltutorial.org/mysql-row_number/

**Comment by mbabker** [comment]
If there is some place in the CMS using the function, then the CMS needs to make version conditional calls.  Alternatively, someone can provide a patch that adjust the query builder's internals to use an alternative implementation if the function doesn't exist.  But the method is just fine to have as part of the API.

The database API can support database functions introduced in newer versions of the supported database platforms, otherwise it wouldn't be possible to introduce JSON related query builder methods for any database driver because MySQL 5.6 doesn't support JSON field types (as one example).

**Comment by mbabker** [comment]
And, in fact, there is a MySQL query builder override in https://github.com/joomla-framework/database/blob/2.0-dev/src/Query/MysqlQueryBuilder.php#L221 which doesn't use the native SQL function.  So, this looks to be not an issue.

**Comment by sakiss** [comment]
Thank you for the answer!

Hence i suppose that the CMS's requirements are not the same the this repo's system requirements.

Though given that this API is used by other APIs (e.g. Table), shouldn't be some check and indirection, to the supported functions in any of those APIs?

For example a call of the `Table::save($someObject, $orderColumnName)`, by an extension developer, can end up to unexpected behaviour, because there is no any check and handling, in the APIs' internal functions about the system.
