### ISSUE TITLE
Offset and limit set two times

### ISSUE THREAD

**Issue by jbanety** [joomla-framework/database#49]
Is there a chance to have limit set two times for a query ?
Example : 
```php
$db    = $this->getDb();
$query = $db->getQuery(true);

$query->select('a.id')
            ->from('#__tests AS a')
            ->where('a.id > 10');

$db->setQuery($query, 0, 1);
$result = $db->loadResult();
```
In `MysqliDriver::setQuery()` we have this :
```php
if ($query instanceof LimitableInterface && !is_null($offset) && !is_null($limit))
{
    $query->setLimit($limit, $offset);
}
```
and then, in `MysqliDriver::execute()` we have :
```php
if ($this->limit > 0 || $this->offset > 0)
{
    $sql .= ' LIMIT ' . $this->offset . ', ' . $this->limit;
}
```
So, my query looks like that :
```sql
SELECT a.id FROM abc_tests WHERE a.id > 10 LIMIT 1 LIMIT 0, 1
```

**Comment by mbabker** [comment]
I know there's an issue similar to this somewhere between here, the old Framework repo, and the CMS repo, because it happens on the PDO MySQL driver too.  For the life of me I can't find it and I can't find if there's been a fix applied.

It in part comes down to the fact that the query objects that use the `PreparableInterface` also have an overriding `setQuery` method in the driver that handles the limit at the point the query's set then in the execute method it's all run again.  Maybe removing the processing from the drivers that have `PreparableInterface` query objects is a valid fix since those overriding `setQuery` methods will inject a raw SQL string into a query object to allow parameter binding to work on those.

**Comment by jbanety** [comment]
what's weird is that this does not happen all the time

**Comment by jbanety** [comment]
Since the query has been prepared and modified by the `MysqliDriver::setQuery` method, we can remove this block below from `MysqliDriver::execute()` :
```php
// Take a local copy so that we don't modify the original query and cause issues later
$sql = $this->replacePrefix((string) $this->sql);

if ($this->limit > 0 || $this->offset > 0)
{
	$sql .= ' LIMIT ' . $this->offset . ', ' . $this->limit;
}
```
`replacePrefix` is also redundant.

On the other hand, it has to be in the `executeUnpreparedQuery`method.

**Comment by asika32764** [comment]
This has been fix in CMS
https://github.com/joomla/joomla-cms/pull/10853

**Comment by jbanety** [comment]
@mbabker 
any chance of a merge in the 2.0-dev branch ?
thx

**Comment by mbabker** [comment]
Done

**Comment by jbanety** [comment]
Thanks very much.
