### ISSUE TITLE
Postgresql / PDO Postgresql Driver issues on Windows

### ISSUE THREAD

**Issue by photodude** [joomla-framework/database#75]
### Steps to reproduce the issue
Review AppVeyor tests in PR #72 

### Expected result
no Postgresql / PDO Postgresql driver issues on windows

### Actual result
the following failures occurred with `GetCollation()` and `GetVersion()`
```bat
There were 4 failures:
1) Joomla\Database\Tests\DriverPgsqlTest::testGetCollation
224
Failed asserting that 'English_United States.1252' contains "UTF-8".
C:\projects\database\Tests\DriverPgsqlTest.php:224
2) Joomla\Database\Tests\DriverPgsqlTest::testGetVersion
465
Failed asserting that '9.4.7' is equal to <string:9.4.7,> or is greater than '9.4.7,'.
C:\projects\database\Tests\DriverPgsqlTest.php:465
3) Joomla\Database\Tests\DriverPostgresqlTest::testGetCollation
224
Failed asserting that 'English_United States.1252' contains "UTF-8".
C:\projects\database\Tests\DriverPostgresqlTest.php:224
4) Joomla\Database\Tests\DriverPostgresqlTest::testGetVersion
465
Failed asserting that '9.4.7' is equal to <string:9.4.7,> or is greater than '9.4.7,'.
C:\projects\database\Tests\DriverPostgresqlTest.php:465
```

### Additional comments
n/a

**Comment by mbabker** [comment]
I think this is just a bad set of tests.

For `testGetVersion`, if I [var_dump the query result](https://github.com/joomla-framework/database/blob/master/Tests/DriverPostgresqlTest.php#L462) it's using for the comparison on my local system, I get this:

```sh
array(1) {
  [0] =>
  string(108) "PostgreSQL 9.5.4 on x86_64-apple-darwin14.5.0, compiled by Apple LLVM version 7.0.2 (clang-700.1.81), 64-bit"
}
```

Same dump on an AppVeyor build:

```sh
array(1) {
  [0]=>
  string(59) "PostgreSQL 9.4.7, compiled by Visual C++ build 1800, 64-bit"
}
```

I'm running a test build that trims the comma off the version number, that's a short hack to make things work.

As for the collation, same test build is also testing specifying the collation when the database is created.  If that change is good, we'll at least have a passing build.

But this indicates the tests need to be improved to be less error prone due to the environment.

**Comment by mbabker** [comment]
The build is now green.

**Comment by photodude** [comment]
I have proposed an alternative fix for the testGetVersion using `preg_match()` which I believe would be more robust to variations in the version string from the `SELECT version();` query. See PR #77
